// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:journey2/firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdzaK36rmTRsrYjkCw5MtzVPfRbt8kZhI',
    appId: '1:754260148515:web:9f3da286496a32d77acc96',
    messagingSenderId: '754260148515',
    projectId: 'ridealongdb-fe563',
    authDomain: 'ridealongdb-fe563.firebaseapp.com',
    storageBucket: 'ridealongdb-fe563.appspot.com',
    measurementId: 'G-4977MK36QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUQlM83e6_lAMEExpNm27m671mUG0C3aU',
    appId: '1:754260148515:android:98cd0f24a07cfa9d7acc96',
    messagingSenderId: '754260148515',
    projectId: 'ridealongdb-fe563',
    storageBucket: 'ridealongdb-fe563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInsk738ytIGyyNOfm119rbUISp65id-0',
    appId: '1:754260148515:ios:8b7cedc22cc1f0227acc96',
    messagingSenderId: '754260148515',
    projectId: 'ridealongdb-fe563',
    storageBucket: 'ridealongdb-fe563.appspot.com',
    iosClientId:
        '754260148515-isl296qr6c9em3maof2nrssqn1pv98bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.journey2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCInsk738ytIGyyNOfm119rbUISp65id-0',
    appId: '1:754260148515:ios:062aa636476e7fd67acc96',
    messagingSenderId: '754260148515',
    projectId: 'ridealongdb-fe563',
    storageBucket: 'ridealongdb-fe563.appspot.com',
    iosClientId:
        '754260148515-bsf9av0ltdns9frc5df4bes23irkps33.apps.googleusercontent.com',
    iosBundleId: 'com.example.journey2.RunnerTests',
  );
}
